// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJaL6E9cMU5-yTLIl1wdSmYPArzgcJzqI',
    appId: '1:791077010396:web:25f16c7cd25e7935952d19',
    messagingSenderId: '791077010396',
    projectId: 'vibeandseek-ac0bc',
    authDomain: 'vibeandseek-ac0bc.firebaseapp.com',
    storageBucket: 'vibeandseek-ac0bc.firebasestorage.app',
    measurementId: 'G-Y55HJJBVML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEkW3J4cMS0dTwC0h7TTa-FvwZxdE_vhE',
    appId: '1:791077010396:android:13ce950c0dd3d7d5952d19',
    messagingSenderId: '791077010396',
    projectId: 'vibeandseek-ac0bc',
    storageBucket: 'vibeandseek-ac0bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgj_Bt4SzoonrglFzyBSToSwDftsWXSnE',
    appId: '1:791077010396:ios:3c6df75284cd237d952d19',
    messagingSenderId: '791077010396',
    projectId: 'vibeandseek-ac0bc',
    storageBucket: 'vibeandseek-ac0bc.firebasestorage.app',
    iosBundleId: 'com.example.projectNameGeorge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgj_Bt4SzoonrglFzyBSToSwDftsWXSnE',
    appId: '1:791077010396:ios:3c6df75284cd237d952d19',
    messagingSenderId: '791077010396',
    projectId: 'vibeandseek-ac0bc',
    storageBucket: 'vibeandseek-ac0bc.firebasestorage.app',
    iosBundleId: 'com.example.projectNameGeorge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJaL6E9cMU5-yTLIl1wdSmYPArzgcJzqI',
    appId: '1:791077010396:web:b7a5a211f4e2eae5952d19',
    messagingSenderId: '791077010396',
    projectId: 'vibeandseek-ac0bc',
    authDomain: 'vibeandseek-ac0bc.firebaseapp.com',
    storageBucket: 'vibeandseek-ac0bc.firebasestorage.app',
    measurementId: 'G-QTC8ZD1XYD',
  );
}
